modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="moneymod"
version="1.0"
displayName="Money Mod"
description='''
Money system mod
'''

[[dependencies.moneymod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.moneymod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,)"
ordering="NONE"
side="BOTH"